### ISSUE TITLE
Setup project with cheminfo:typescript

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/wdf-parser#2]
Can we prepare the project for typescript while still programming in javascript ?

I did

`yo cheminfo:typescript`

I renamed the '.ts' to '.js' but this is maybe useless

I have errors because of some dependencies that do not have typescript definition.

@targos We could discuss about this tomorrow

**Comment by targos** [comment]
you can write JS in `.ts` files. I think just need to make the tsconfig less strict
